on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{secrets.PAT_TOKEN}}

    #- name: Setup Git

    #- name: Get latest tag

    #- name: Analyze commit message

    #- name: Determine new version

    #- name: Create new tag

    #- name: Show new version