on:
  push:
    branches:
      - "main"

env:
  LATEST_TAG:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{secrets.PAT_TOKEN}}

    - name: Setup Git
      run: |
        git config --global user.name ${{vars.username}}
        git config --global user.email ${{vars.email}}

    - name: Get latest tag
      run: |
        echo git describe --tags --abbrev=0 >> $LATEST_TAG

    #- name: Analyze commit message fix
      
    #  if: ${{ contains(git log --format=%B -n 1, 'fix') }}
    #  run: echo yes

    #- name: Analyze commit message feat
    #  if: $GITHUB_ENV == "feat"

    #- name: Analyze commit message breakingChange
    #  if: $GITHUB_ENV == "breakingChange"

    #- name: Determine new version

    #- name: Create new tag

    #- name: Show new version