on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      env:
        PAT_TOKEN: ${{secrets.PAT_TOKEN}}
      with:
        token: $PAT_TOKEN

    - name: Setup Git

    - name: Get latest tag

    - name: Analyze commit message

    - name: Determine new version

    - name: Create new tag

    - name: Show new version